# -*- coding: utf-8 -*-
"""IA_jogo_velha.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-EL66dhxlLB3RMowY6ZQ_AA17JltXay3
"""

# !pip uninstall sklearn
# !pip uninstall scikit-learn
# !pip install sklearn

import pandas as pd  # importando a bibliotecas pandas
from sklearn.datasets import load_digits
from sklearn.linear_model import Perceptron

df_tic_tac_toe = pd.read_csv("tic-tac-toe.csv")  # Lendo o arquivo csv e armazendano em um dataframe

df_tic_tac_toe.isna().any() # verificando campo vazio que pode quebrar o sistema

df_tic_tac_toe.head() # vendo como estapo os dados

df_tic_tac_toe.replace({'o' :-1 , 'b' : 0 , 'x': 1 , 'positivo' : 1 , 'negativo':-1 }) # Replace tudo para numero

def sklearn_to_df(sklearn_dataset):
  df = pd.DataFrame(sklearn_dataset.data, columns=sklearn_dataset.feature_names)
  df["target"] = pd.Series(sklearn_dataset.target)

  return df